on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  check_cargo_fmt:
    name: Check that 'cargo fmt' has been run
    runs-on: ubuntu-22.04
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v4
        with:
          components: rustfmt
      - run: cargo fmt --check

  check_cargo_clippy:
    name: Check that 'cargo clippy' has no warnings
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get install pkg-config libssl-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: actions/checkout@v4
      - run: cargo clippy --all-targets --all-features -- -Dwarnings
